const productDetail = {
  currency: 'USD',
  eventName: 'vtex:productView',
  event: 'productView',
  product: {
    cacheId: 'classic-shoes',
    productName: 'Classic Shoes Top',
    productId: '16',
    description: "If you go classic, you can't go wrong.",
    titleTag: 'Classic Shoes',
    metaTagDescription: "If you go classic, you can't go wrong.",
    linkText: 'classic-shoes',
    productReference: null,
    categories: ['/Apparel & Accessories/Shoes/', '/Apparel & Accessories/'],
    categoryId: '10',
    categoriesIds: ['/25/10/', '/25/'],
    brand: 'Mizuno',
    brandId: 2000010,
    properties: [],
    specificationGroups: [
      {
        name: 'allSpecifications',
        specifications: [],
        __typename: 'SpecificationGroup',
      },
    ],
    items: [
      {
        itemId: '35',
        name: 'Classic Pink',
        nameComplete: 'Classic Shoes Top Classic Pink',
        complementName:
          'Os corredores de alta performance terão um grande aliado com o Tênis Mizuno Wave Viper 3 Masculino. A placa Wave de ponta a ponta garante um amortecimento responsivo do começo ao fim da corrida.',
        ean: '80098',
        referenceId: [
          {
            Key: 'RefId',
            Value: '12531',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155470',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155470-#width#-#height#/Frame-11.jpg?v=636793763155730000" width="#width#" height="#height#" alt="Frame-11" id="" />',
            imageUrl:
              'https://storecomponents.vteximg.com.br/arquivos/ids/155470/Frame-11.jpg?v=636793763155730000',
            imageText: 'Frame-11',
            __typename: 'Image',
          },
          {
            imageId: '155471',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155471-#width#-#height#/Frame-10.jpg?v=637018188181300000" width="#width#" height="#height#" alt="Frame-10" id="" />',
            imageUrl:
              'https://storecomponents.vteximg.com.br/arquivos/ids/155471/Frame-10.jpg?v=637018188181300000',
            imageText: 'Frame-10',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=35&qty=1&seller=1&sc=1&price=3890&cv=d1d26b494a83cac2e7812d2818e8ed1e_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 38.9,
              ListPrice: 38.9,
              PriceWithoutDiscount: 38.9,
              RewardValue: 0,
              PriceValidUntil: '2020-09-05T22:07:59.9154441Z',
              AvailableQuantity: 2000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                'd1d26b494a83cac2e7812d2818e8ed1e_',
              Installments: [
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 19.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 13,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 19.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 13,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 19.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 13,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Tamanho',
            values: ['40'],
            __typename: 'Property',
          },
          {
            name: 'Cor',
            values: ['Verde'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [],
        calculatedAttachments: null,
        __typename: 'SKU',
      },
      {
        itemId: '36',
        name: 'White Slip On',
        nameComplete: 'Classic Shoes Top White Slip On',
        complementName:
          'Os corredores de alta performance terão um grande aliado com o Tênis Mizuno Wave Viper 3 Masculino. A placa Wave de ponta a ponta garante um amortecimento responsivo do começo ao fim da corrida.',
        ean: '80099',
        referenceId: [
          {
            Key: 'RefId',
            Value: '12532',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155472',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155472-#width#-#height#/Frame-3.jpg?v=636793763985400000" width="#width#" height="#height#" alt="Frame-3" id="" />',
            imageUrl:
              'https://storecomponents.vteximg.com.br/arquivos/ids/155472/Frame-3.jpg?v=636793763985400000',
            imageText: 'Frame-3',
            __typename: 'Image',
          },
          {
            imageId: '155473',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155473-#width#-#height#/Frame.jpg?v=636793764101900000" width="#width#" height="#height#" alt="Frame" id="" />',
            imageUrl:
              'https://storecomponents.vteximg.com.br/arquivos/ids/155473/Frame.jpg?v=636793764101900000',
            imageText: 'Frame',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=36&qty=1&seller=1&sc=1&price=26250&cv=d1d26b494a83cac2e7812d2818e8ed1e_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 262.5,
              ListPrice: 262.5,
              PriceWithoutDiscount: 262.5,
              RewardValue: 0,
              PriceValidUntil: '2020-09-05T22:08:00.0271609Z',
              AvailableQuantity: 2000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                'd1d26b494a83cac2e7812d2818e8ed1e_',
              Installments: [
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 131.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 2,
                  Name: 'Visa 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 3,
                  Name: 'Visa 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 65.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 4,
                  Name: 'Visa 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 52.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 5,
                  Name: 'Visa 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 43.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 6,
                  Name: 'Visa 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 131.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 2,
                  Name: 'Mastercard 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 3,
                  Name: 'Mastercard 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 65.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 4,
                  Name: 'Mastercard 4 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 52.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 5,
                  Name: 'Mastercard 5 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 43.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 6,
                  Name: 'Mastercard 6 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 131.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 87.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Tamanho',
            values: ['41'],
            __typename: 'Property',
          },
          {
            name: 'Cor',
            values: ['Cinza'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [],
        calculatedAttachments: null,
        __typename: 'SKU',
      },
      {
        itemId: '37',
        name: 'Cool Pink',
        nameComplete: 'Classic Shoes Top Cool Pink',
        complementName:
          'Os corredores de alta performance terão um grande aliado com o Tênis Mizuno Wave Viper 3 Masculino. A placa Wave de ponta a ponta garante um amortecimento responsivo do começo ao fim da corrida.',
        ean: '80100',
        referenceId: [
          {
            Key: 'RefId',
            Value: '12533',
            __typename: 'Reference',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        images: [
          {
            imageId: '155474',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155474-#width#-#height#/Frame-1.jpg?v=636793764631500000" width="#width#" height="#height#" alt="Frame-1" id="" />',
            imageUrl:
              'https://storecomponents.vteximg.com.br/arquivos/ids/155474/Frame-1.jpg?v=636793764631500000',
            imageText: 'Frame-1',
            __typename: 'Image',
          },
          {
            imageId: '155475',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155475-#width#-#height#/Frame-2.jpg?v=636793764763600000" width="#width#" height="#height#" alt="Frame-2" id="" />',
            imageUrl:
              'https://storecomponents.vteximg.com.br/arquivos/ids/155475/Frame-2.jpg?v=636793764763600000',
            imageText: 'Frame-2',
            __typename: 'Image',
          },
        ],
        videos: [],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=37&qty=1&seller=1&sc=1&price=1050&cv=d1d26b494a83cac2e7812d2818e8ed1e_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              discountHighlights: [],
              teasers: [],
              Price: 10.5,
              ListPrice: 10.5,
              PriceWithoutDiscount: 10.5,
              RewardValue: 0,
              PriceValidUntil: '2020-09-05T22:07:59.9387089Z',
              AvailableQuantity: 1000000,
              Tax: 0,
              CacheVersionUsedToCallCheckout:
                'd1d26b494a83cac2e7812d2818e8ed1e_',
              Installments: [
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  Name: 'American Express à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  Name: 'Visa à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  Name: 'Mastercard à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  Name: 'Boleto Bancário à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  Name: 'Promissory à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  Name: 'Customer Credit à vista',
                  __typename: 'Installment',
                },
                {
                  Value: 5.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 2,
                  Name: 'Customer Credit 2 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 3.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 3,
                  Name: 'Customer Credit 3 vezes sem juros',
                  __typename: 'Installment',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  Name: 'Free à vista',
                  __typename: 'Installment',
                },
              ],
              __typename: 'Offer',
            },
            __typename: 'Seller',
          },
        ],
        variations: [
          {
            name: 'Tamanho',
            values: ['42'],
            __typename: 'Property',
          },
          {
            name: 'Cor',
            values: ['Preto'],
            __typename: 'Property',
          },
        ],
        kitItems: [],
        attachments: [],
        calculatedAttachments: null,
        __typename: 'SKU',
      },
    ],
    itemMetadata: null,
    productClusters: [],
    clusterHighlights: [],
    __typename: 'Product',
    benefits: [],
    selectedSku: {
      itemId: '35',
      name: 'Classic Pink',
      nameComplete: 'Classic Shoes Top Classic Pink',
      complementName:
        'Os corredores de alta performance terão um grande aliado com o Tênis Mizuno Wave Viper 3 Masculino. A placa Wave de ponta a ponta garante um amortecimento responsivo do começo ao fim da corrida.',
      ean: '80098',
      referenceId: [
        {
          Key: 'RefId',
          Value: '12531',
          __typename: 'Reference',
        },
      ],
      measurementUnit: 'un',
      unitMultiplier: 1,
      images: [
        {
          imageId: '155470',
          imageLabel: '',
          imageTag:
            '<img src="~/arquivos/ids/155470-#width#-#height#/Frame-11.jpg?v=636793763155730000" width="#width#" height="#height#" alt="Frame-11" id="" />',
          imageUrl:
            'https://storecomponents.vteximg.com.br/arquivos/ids/155470/Frame-11.jpg?v=636793763155730000',
          imageText: 'Frame-11',
          __typename: 'Image',
        },
        {
          imageId: '155471',
          imageLabel: '',
          imageTag:
            '<img src="~/arquivos/ids/155471-#width#-#height#/Frame-10.jpg?v=637018188181300000" width="#width#" height="#height#" alt="Frame-10" id="" />',
          imageUrl:
            'https://storecomponents.vteximg.com.br/arquivos/ids/155471/Frame-10.jpg?v=637018188181300000',
          imageText: 'Frame-10',
          __typename: 'Image',
        },
      ],
      videos: [],
      sellers: [
        {
          sellerId: '1',
          sellerName: 'VTEX',
          addToCartLink:
            'https://portal.vtexcommercestable.com.br/checkout/cart/add?sku=35&qty=1&seller=1&sc=1&price=3890&cv=d1d26b494a83cac2e7812d2818e8ed1e_&sc=1',
          sellerDefault: true,
          commertialOffer: {
            discountHighlights: [],
            teasers: [],
            Price: 1540.99,
            ListPrice: 1900.99,
            // PriceWithoutDiscount: 38.9, the current event does not send this.
            RewardValue: 0,
            PriceValidUntil: '2020-09-05T22:07:59.9154441Z',
            AvailableQuantity: 2000000,
            Tax: 0,
            CacheVersionUsedToCallCheckout: 'd1d26b494a83cac2e7812d2818e8ed1e_',
            Installments: [
              {
                Value: 38.9,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 1,
                Name: 'American Express à vista',
                __typename: 'Installment',
              },
              {
                Value: 38.9,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 1,
                Name: 'Visa à vista',
                __typename: 'Installment',
              },
              {
                Value: 19.5,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 2,
                Name: 'Visa 2 vezes sem juros',
                __typename: 'Installment',
              },
              {
                Value: 13,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 3,
                Name: 'Visa 3 vezes sem juros',
                __typename: 'Installment',
              },
              {
                Value: 38.9,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 1,
                Name: 'Mastercard à vista',
                __typename: 'Installment',
              },
              {
                Value: 19.5,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 2,
                Name: 'Mastercard 2 vezes sem juros',
                __typename: 'Installment',
              },
              {
                Value: 13,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 3,
                Name: 'Mastercard 3 vezes sem juros',
                __typename: 'Installment',
              },
              {
                Value: 38.9,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 1,
                Name: 'Boleto Bancário à vista',
                __typename: 'Installment',
              },
              {
                Value: 38.9,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 1,
                Name: 'Promissory à vista',
                __typename: 'Installment',
              },
              {
                Value: 38.9,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 1,
                Name: 'Customer Credit à vista',
                __typename: 'Installment',
              },
              {
                Value: 19.5,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 2,
                Name: 'Customer Credit 2 vezes sem juros',
                __typename: 'Installment',
              },
              {
                Value: 13,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 3,
                Name: 'Customer Credit 3 vezes sem juros',
                __typename: 'Installment',
              },
              {
                Value: 38.9,
                InterestRate: 0,
                TotalValuePlusInterestRate: 38.9,
                NumberOfInstallments: 1,
                Name: 'Free à vista',
                __typename: 'Installment',
              },
            ],
            __typename: 'Offer',
          },
          __typename: 'Seller',
        },
      ],
      variations: [
        {
          name: 'Tamanho',
          values: ['40'],
          __typename: 'Property',
        },
        {
          name: 'Cor',
          values: ['Verde'],
          __typename: 'Property',
        },
      ],
      kitItems: [],
      attachments: [],
      calculatedAttachments: null,
      __typename: 'SKU',
    },
  },
  list: 'List of products',
}

export default productDetail
